### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by radnov** [MarwanDebbiche/pylambdarest#5]
Given that there are no tests and I like your idea here, I would like to help with writing some and ensuring automated linting, etc for the repository.

Let me know if that is okay with you and if you have any preferences or vision on what and how should things be structured. Also, whether you have any progress on those matters so far.

My idea is to have a *_test.py for each of the source files and add some linting and static analisys via flake8, mypy and maybe even pre-commit as a starter.

**Comment by MarwanDebbiche** [comment]
Hello @radnov ,

I received your email, it would indeed be very useful if you could help me add some tests, thank you very much for offering to do so.

What you suggested is fine by me:

> a *_test.py for each of the source files and add some linting and static analysis via flake8, mypy and maybe even pre-commit as a starter

Could you open a PR ?

**Comment by radnov** [comment]
Meanwhile I got over-busy and can't really spend more time on this for now, but I'm still up for it.  
Here's a [PR with my current progress](https://github.com/MarwanDebbiche/pylambdarest/pull/6) - tests for the `request` module.  
Let me know what you think.

**Comment by MarwanDebbiche** [comment]
@radnov thanks for your work. I will merge it in a `feature/tests` branch as suggested and continue from there.

**Comment by MarwanDebbiche** [comment]
Closing this issue as i added some tests with 100% coverage. Those tests are executed on push using Github actions.
I also added flake8, mypy, black and pre-commit for linting and static analysis.

I think more could be done in terms of QA, but for now I will focus on adding features to pylambdarest.

**Comment by radnov** [comment]
Very nice! You now have a great foundation to build upon. 🚀
